/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.JPopupMenu;
import java.io.*;


public class Home extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents(); 
        setLocationRelativeTo(null);
        
    }
    
    
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        HomeMainPanel = new javax.swing.JPanel();
        NavBarHome = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        usethisDashboard = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        UserName = new javax.swing.JLabel();
        EmailUser = new javax.swing.JLabel();
        BottomProfileUserHome = new javax.swing.JLabel();
        DocumentButton = new javax.swing.JPanel();
        IconDocument = new javax.swing.JLabel();
        DocumentCombobox = new javax.swing.JComboBox<>();
        jButtonProject = new javax.swing.JButton();
        jbuttonReporting = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonTax = new javax.swing.JButton();
        jButtonSetting = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        HomeDashboard = new javax.swing.JPanel();
        WelcomebackUsername = new javax.swing.JLabel();
        HereWhatGoing = new javax.swing.JLabel();
        IconBellHome = new javax.swing.JLabel();
        DateHomePanel = new javax.swing.JLabel();
        NumberPanelDarkblue = new javax.swing.JPanel();
        IconDarkblue = new javax.swing.JLabel();
        LabelNumberDarkblue = new javax.swing.JLabel();
        TextDarkblue = new javax.swing.JTextField();
        TopProfileHome = new javax.swing.JPanel();
        ProfielUserHome = new javax.swing.JLabel();
        NumberUserHome = new javax.swing.JLabel();
        NumberPanelBlue = new javax.swing.JPanel();
        IconBlue = new javax.swing.JLabel();
        LabelNumberBlue = new javax.swing.JLabel();
        TextBlue = new javax.swing.JTextField();
        NumberPanelRed = new javax.swing.JPanel();
        IconRed = new javax.swing.JLabel();
        LabelNumberRed = new javax.swing.JLabel();
        TextRed = new javax.swing.JTextField();
        EmptyPanelTopRight = new javax.swing.JPanel();
        EmptyPanelTopLeft = new javax.swing.JPanel();
        EmptyPanelBottomLeft = new javax.swing.JPanel();
        EmptyPanelBottomRight = new javax.swing.JPanel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1440, 1020));

        HomeMainPanel.setLayout(new java.awt.BorderLayout());

        NavBarHome.setBackground(new java.awt.Color(255, 255, 255));
        NavBarHome.setPreferredSize(new java.awt.Dimension(340, 1020));

        jSeparator1.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator1.setForeground(new java.awt.Color(136, 136, 136));

        usethisDashboard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usethisDashboard.setText("Usethis Dashboard");

        Logo.setIcon(new javax.swing.ImageIcon("D:\\OOP JAVA LAB\\Project\\src\\image\\Logo.png.png")); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator2.setForeground(new java.awt.Color(136, 136, 136));

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserName.setText("Username");

        EmailUser.setForeground(new java.awt.Color(136, 136, 136));
        EmailUser.setText("Email");

        BottomProfileUserHome.setIcon(new javax.swing.ImageIcon("D:\\OOP JAVA LAB\\Project\\src\\image\\Ellipse 2 (1).png")); // NOI18N

        DocumentButton.setBackground(new java.awt.Color(255, 255, 255));

        IconDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_page-edit.png"))); // NOI18N

        DocumentCombobox.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        DocumentCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document", "Quotation", "Recipt" }));
        DocumentCombobox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        DocumentCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DocumentButtonLayout = new javax.swing.GroupLayout(DocumentButton);
        DocumentButton.setLayout(DocumentButtonLayout);
        DocumentButtonLayout.setHorizontalGroup(
            DocumentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(IconDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DocumentCombobox, 0, 269, Short.MAX_VALUE))
        );
        DocumentButtonLayout.setVerticalGroup(
            DocumentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DocumentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DocumentCombobox)
                    .addGroup(DocumentButtonLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(IconDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jButtonProject.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_app-window.png"))); // NOI18N
        jButtonProject.setText("  Project");
        jButtonProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjectActionPerformed(evt);
            }
        });

        jbuttonReporting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jbuttonReporting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_stats-report.png"))); // NOI18N
        jbuttonReporting.setText("  Reporting");
        jbuttonReporting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jbuttonReporting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbuttonReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonReportingActionPerformed(evt);
            }
        });

        jButtonUser.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_user-square.png"))); // NOI18N
        jButtonUser.setText("  Users");
        jButtonUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });

        jButtonTax.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_calculator.png"))); // NOI18N
        jButtonTax.setText("  Tax");
        jButtonTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonTax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxActionPerformed(evt);
            }
        });

        jButtonSetting.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_settings.png"))); // NOI18N
        jButtonSetting.setText("  Setting");
        jButtonSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingActionPerformed(evt);
            }
        });

        jButtonHome.setBackground(new java.awt.Color(224, 227, 232));
        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_home-simple-door.png"))); // NOI18N
        jButtonHome.setText("  Home");
        jButtonHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarHomeLayout = new javax.swing.GroupLayout(NavBarHome);
        NavBarHome.setLayout(NavBarHomeLayout);
        NavBarHomeLayout.setHorizontalGroup(
            NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(NavBarHomeLayout.createSequentialGroup()
                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarHomeLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(usethisDashboard))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarHomeLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(BottomProfileUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserName)
                                .addComponent(EmailUser)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarHomeLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(DocumentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(NavBarHomeLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbuttonReporting, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                .addComponent(jButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        NavBarHomeLayout.setVerticalGroup(
            NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarHomeLayout.createSequentialGroup()
                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarHomeLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usethisDashboard)
                        .addGap(42, 42, 42)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProject, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NavBarHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarHomeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(UserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailUser))
                    .addGroup(NavBarHomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BottomProfileUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        Logo.getAccessibleContext().setAccessibleName("LOGO");

        HomeMainPanel.add(NavBarHome, java.awt.BorderLayout.WEST);

        HomeDashboard.setBackground(new java.awt.Color(236, 239, 243));

        WelcomebackUsername.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        WelcomebackUsername.setText("Welcome back, Username");

        HereWhatGoing.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        HereWhatGoing.setForeground(new java.awt.Color(163, 165, 171));
        HereWhatGoing.setText("Here’s what’s going on with your company status.");

        IconBellHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ph_bell.png"))); // NOI18N

        DateHomePanel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DateHomePanel.setForeground(new java.awt.Color(136, 136, 136));
        DateHomePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circum_calendar-date.png"))); // NOI18N
        DateHomePanel.setText("Friday, July 10,2024");

        NumberPanelDarkblue.setBackground(new java.awt.Color(255, 255, 255));
        NumberPanelDarkblue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        IconDarkblue.setBackground(new java.awt.Color(255, 255, 255));
        IconDarkblue.setIcon(new javax.swing.ImageIcon("D:\\OOP JAVA LAB\\Project\\src\\image\\Rectangle 45.png")); // NOI18N

        LabelNumberDarkblue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelNumberDarkblue.setText("Number");

        TextDarkblue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextDarkblue.setForeground(new java.awt.Color(136, 136, 136));
        TextDarkblue.setText("descition..");
        TextDarkblue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextDarkblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDarkblueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NumberPanelDarkblueLayout = new javax.swing.GroupLayout(NumberPanelDarkblue);
        NumberPanelDarkblue.setLayout(NumberPanelDarkblueLayout);
        NumberPanelDarkblueLayout.setHorizontalGroup(
            NumberPanelDarkblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelDarkblueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconDarkblue)
                .addGap(18, 18, 18)
                .addGroup(NumberPanelDarkblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextDarkblue)
                    .addComponent(LabelNumberDarkblue, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        NumberPanelDarkblueLayout.setVerticalGroup(
            NumberPanelDarkblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelDarkblueLayout.createSequentialGroup()
                .addGroup(NumberPanelDarkblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumberPanelDarkblueLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconDarkblue, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelDarkblueLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelNumberDarkblue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextDarkblue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        TopProfileHome.setBackground(new java.awt.Color(255, 255, 255));

        ProfielUserHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ellipse 2 (1).png"))); // NOI18N

        NumberUserHome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NumberUserHome.setText("Number");

        javax.swing.GroupLayout TopProfileHomeLayout = new javax.swing.GroupLayout(TopProfileHome);
        TopProfileHome.setLayout(TopProfileHomeLayout);
        TopProfileHomeLayout.setHorizontalGroup(
            TopProfileHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopProfileHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfielUserHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(NumberUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopProfileHomeLayout.setVerticalGroup(
            TopProfileHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopProfileHomeLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(ProfielUserHome)
                .addGap(18, 18, 18))
            .addGroup(TopProfileHomeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(NumberUserHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumberPanelBlue.setBackground(new java.awt.Color(255, 255, 255));
        NumberPanelBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        IconBlue.setBackground(new java.awt.Color(255, 255, 255));
        IconBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 45 (1)_1.png"))); // NOI18N

        LabelNumberBlue.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelNumberBlue.setText("Number");

        TextBlue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextBlue.setForeground(new java.awt.Color(136, 136, 136));
        TextBlue.setText("descition..");
        TextBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBlueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NumberPanelBlueLayout = new javax.swing.GroupLayout(NumberPanelBlue);
        NumberPanelBlue.setLayout(NumberPanelBlueLayout);
        NumberPanelBlueLayout.setHorizontalGroup(
            NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconBlue)
                .addGap(18, 18, 18)
                .addGroup(NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextBlue)
                    .addComponent(LabelNumberBlue, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        NumberPanelBlueLayout.setVerticalGroup(
            NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                .addGroup(NumberPanelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelBlueLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelNumberBlue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        NumberPanelRed.setBackground(new java.awt.Color(255, 255, 255));
        NumberPanelRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        IconRed.setBackground(new java.awt.Color(255, 255, 255));
        IconRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rectangle 45 (2).png"))); // NOI18N

        LabelNumberRed.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LabelNumberRed.setText("Number");

        TextRed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextRed.setForeground(new java.awt.Color(136, 136, 136));
        TextRed.setText("descition..");
        TextRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TextRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NumberPanelRedLayout = new javax.swing.GroupLayout(NumberPanelRed);
        NumberPanelRed.setLayout(NumberPanelRedLayout);
        NumberPanelRedLayout.setHorizontalGroup(
            NumberPanelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelRedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconRed)
                .addGap(18, 18, 18)
                .addGroup(NumberPanelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextRed)
                    .addComponent(LabelNumberRed, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        NumberPanelRedLayout.setVerticalGroup(
            NumberPanelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberPanelRedLayout.createSequentialGroup()
                .addGroup(NumberPanelRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NumberPanelRedLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconRed, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NumberPanelRedLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelNumberRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextRed, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        EmptyPanelTopRight.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EmptyPanelTopRightLayout = new javax.swing.GroupLayout(EmptyPanelTopRight);
        EmptyPanelTopRight.setLayout(EmptyPanelTopRightLayout);
        EmptyPanelTopRightLayout.setHorizontalGroup(
            EmptyPanelTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        EmptyPanelTopRightLayout.setVerticalGroup(
            EmptyPanelTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        EmptyPanelTopLeft.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EmptyPanelTopLeftLayout = new javax.swing.GroupLayout(EmptyPanelTopLeft);
        EmptyPanelTopLeft.setLayout(EmptyPanelTopLeftLayout);
        EmptyPanelTopLeftLayout.setHorizontalGroup(
            EmptyPanelTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EmptyPanelTopLeftLayout.setVerticalGroup(
            EmptyPanelTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        EmptyPanelBottomLeft.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EmptyPanelBottomLeftLayout = new javax.swing.GroupLayout(EmptyPanelBottomLeft);
        EmptyPanelBottomLeft.setLayout(EmptyPanelBottomLeftLayout);
        EmptyPanelBottomLeftLayout.setHorizontalGroup(
            EmptyPanelBottomLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        EmptyPanelBottomLeftLayout.setVerticalGroup(
            EmptyPanelBottomLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        EmptyPanelBottomRight.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout EmptyPanelBottomRightLayout = new javax.swing.GroupLayout(EmptyPanelBottomRight);
        EmptyPanelBottomRight.setLayout(EmptyPanelBottomRightLayout);
        EmptyPanelBottomRightLayout.setHorizontalGroup(
            EmptyPanelBottomRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EmptyPanelBottomRightLayout.setVerticalGroup(
            EmptyPanelBottomRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HomeDashboardLayout = new javax.swing.GroupLayout(HomeDashboard);
        HomeDashboard.setLayout(HomeDashboardLayout);
        HomeDashboardLayout.setHorizontalGroup(
            HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeDashboardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeDashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WelcomebackUsername)
                            .addComponent(HereWhatGoing))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeDashboardLayout.createSequentialGroup()
                                .addComponent(IconBellHome)
                                .addGap(18, 18, 18)
                                .addComponent(TopProfileHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addComponent(DateHomePanel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(HomeDashboardLayout.createSequentialGroup()
                            .addComponent(EmptyPanelBottomLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(EmptyPanelBottomRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HomeDashboardLayout.createSequentialGroup()
                            .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(HomeDashboardLayout.createSequentialGroup()
                                    .addComponent(NumberPanelDarkblue, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(NumberPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(EmptyPanelTopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmptyPanelTopRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NumberPanelRed, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39))
        );
        HomeDashboardLayout.setVerticalGroup(
            HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeDashboardLayout.createSequentialGroup()
                .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeDashboardLayout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomeDashboardLayout.createSequentialGroup()
                                .addComponent(TopProfileHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeDashboardLayout.createSequentialGroup()
                                .addComponent(IconBellHome)
                                .addGap(31, 31, 31)))
                        .addComponent(DateHomePanel)
                        .addGap(31, 31, 31))
                    .addGroup(HomeDashboardLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(WelcomebackUsername)
                        .addGap(18, 18, 18)
                        .addComponent(HereWhatGoing)))
                .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NumberPanelDarkblue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberPanelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberPanelRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmptyPanelTopRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmptyPanelTopLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HomeDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmptyPanelBottomLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmptyPanelBottomRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        HomeMainPanel.add(HomeDashboard, java.awt.BorderLayout.CENTER);

        getContentPane().add(HomeMainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void TextDarkblueActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void DocumentComboboxActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    String selectedDocument = (String) DocumentCombobox.getSelectedItem();
    
    switch (selectedDocument) {
        case "Document":
            break;
        case "Quotation":
            openQuotition();
            break;
        case "Recipt":
            openReceipt();
            break;
        default:
            break;
    }
}
    private void openQuotition() {
    Quotition registerForm = new Quotition();
    registerForm.setVisible(true);
    }
    
    private void openReceipt() {
    Receipt registerForm = new Receipt();
    registerForm.setVisible(true);
    }
                                                

    private void TextBlueActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void TextRedActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jButtonProjectActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        Projecct registerForm = new Projecct();
        registerForm.setVisible(true);
        jButtonProject.addActionListener(new Home());
    }                                              

    private void jButtonSettingActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void jButtonTaxActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jbuttonReportingActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        Report registerForm = new Report();
        registerForm.setVisible(true);
        jbuttonReporting.addActionListener(new Home());
    }                                                

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        Home registerForm = new Home();
        registerForm.setVisible(true);
        jButtonHome.addActionListener(new Home());
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BottomProfileUserHome;
    private javax.swing.JLabel DateHomePanel;
    private javax.swing.JPanel DocumentButton;
    private javax.swing.JComboBox<String> DocumentCombobox;
    private javax.swing.JLabel EmailUser;
    private javax.swing.JPanel EmptyPanelBottomLeft;
    private javax.swing.JPanel EmptyPanelBottomRight;
    private javax.swing.JPanel EmptyPanelTopLeft;
    private javax.swing.JPanel EmptyPanelTopRight;
    private javax.swing.JLabel HereWhatGoing;
    private javax.swing.JPanel HomeDashboard;
    private javax.swing.JPanel HomeMainPanel;
    private javax.swing.JLabel IconBellHome;
    private javax.swing.JLabel IconBlue;
    private javax.swing.JLabel IconDarkblue;
    private javax.swing.JLabel IconDocument;
    private javax.swing.JLabel IconRed;
    private javax.swing.JLabel LabelNumberBlue;
    private javax.swing.JLabel LabelNumberDarkblue;
    private javax.swing.JLabel LabelNumberRed;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel NavBarHome;
    private javax.swing.JPanel NumberPanelBlue;
    private javax.swing.JPanel NumberPanelDarkblue;
    private javax.swing.JPanel NumberPanelRed;
    private javax.swing.JLabel NumberUserHome;
    private javax.swing.JLabel ProfielUserHome;
    private javax.swing.JTextField TextBlue;
    private javax.swing.JTextField TextDarkblue;
    private javax.swing.JTextField TextRed;
    private javax.swing.JPanel TopProfileHome;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel WelcomebackUsername;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonProject;
    private javax.swing.JButton jButtonSetting;
    private javax.swing.JButton jButtonTax;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbuttonReporting;
    private javax.swing.JLabel usethisDashboard;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
