package project;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author asus
 */
public class Receipt extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Quotition
     */
    public Receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        namelabel = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        infolabel = new javax.swing.JLabel();
        ziptext = new javax.swing.JTextField();
        taxidtext = new javax.swing.JTextField();
        officetext = new javax.swing.JTextField();
        totallabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sellerlabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        sellertext = new javax.swing.JTextField();
        datetext = new javax.swing.JTextField();
        Refnumlabel = new javax.swing.JLabel();
        refnumtext = new javax.swing.JTextField();
        detaillabel = new javax.swing.JLabel();
        detailtext = new javax.swing.JTextField();
        projectlabel = new javax.swing.JLabel();
        projecttext = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        namepricetext1 = new javax.swing.JTextField();
        namepricetext2 = new javax.swing.JTextField();
        quantitytext = new javax.swing.JTextField();
        unittext = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        totalnumnum = new javax.swing.JLabel();
        namepricelabel = new javax.swing.JLabel();
        totalpricelabel = new javax.swing.JLabel();
        quantitylabel = new javax.swing.JLabel();
        perpricelabel = new javax.swing.JLabel();
        numlabel = new javax.swing.JLabel();
        totalnum = new javax.swing.JLabel();
        addlistbutton = new javax.swing.JButton();
        notelabel = new javax.swing.JLabel();
        percentlabel = new javax.swing.JLabel();
        totalmoneylabel = new javax.swing.JLabel();
        totaldiscountlabel = new javax.swing.JLabel();
        alltotallabel = new javax.swing.JLabel();
        alltotalnum = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        discountnum = new javax.swing.JLabel();
        totaldiscountnum = new javax.swing.JLabel();
        discounttext = new javax.swing.JTextField();
        discountlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infotext = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        notetextarea = new javax.swing.JTextArea();
        serielabel = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        headerlabel = new javax.swing.JLabel();
        closebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setSize(new java.awt.Dimension(1440, 1024));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        namelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namelabel.setText("ชื่อลูกค้า:");

        nametext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nametext.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });

        infolabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        infolabel.setText("ข้อมูลลูกค้า:");

        ziptext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ziptext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ziptextActionPerformed(evt);
            }
        });

        taxidtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taxidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxidtextActionPerformed(evt);
            }
        });

        officetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        officetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officetextActionPerformed(evt);
            }
        });

        totallabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totallabel.setText("ยอดรวมทั้งสิ้น:");

        sellerlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sellerlabel.setText("พนักงานขาย:");

        datelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datelabel.setText("วันที่:");

        sellertext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sellertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellertextActionPerformed(evt);
            }
        });

        datetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetextActionPerformed(evt);
            }
        });

        Refnumlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Refnumlabel.setText("หมายเลขอ้างอิง:");

        refnumtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refnumtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refnumtextActionPerformed(evt);
            }
        });

        detaillabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        detaillabel.setText("รายละเอียด");

        detailtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        detailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailtextActionPerformed(evt);
            }
        });

        projectlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        projectlabel.setText("โปรเจ็ค:");

        projecttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        projecttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projecttextActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("1");

        namepricetext1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namepricetext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namepricetext1ActionPerformed(evt);
            }
        });

        namepricetext2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namepricetext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namepricetext2ActionPerformed(evt);
            }
        });

        quantitytext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantitytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytextActionPerformed(evt);
            }
        });

        unittext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        unittext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unittextActionPerformed(evt);
            }
        });

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        totalnumnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalnumnum.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namepricetext1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(namepricetext2))
                .addGap(155, 155, 155)
                .addComponent(quantitytext, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unittext, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(1219, Short.MAX_VALUE)
                    .addComponent(totalnumnum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namepricetext1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namepricetext2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unittext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantitytext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(29, Short.MAX_VALUE)
                    .addComponent(totalnumnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        namepricelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        namepricelabel.setText("ชื่อสินค้า / ราคาหน่วย");

        totalpricelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalpricelabel.setText("ราคารวม");

        quantitylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantitylabel.setText("จํานวน             หน่วย");

        perpricelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perpricelabel.setText("ราคาต่อหน่วย");

        numlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numlabel.setText("ลําดับ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(numlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(namepricelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(quantitylabel)
                .addGap(131, 131, 131)
                .addComponent(perpricelabel)
                .addGap(123, 123, 123)
                .addComponent(totalpricelabel)
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namepricelabel)
                    .addComponent(totalpricelabel)
                    .addComponent(quantitylabel)
                    .addComponent(perpricelabel)
                    .addComponent(numlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        totalnum.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        totalnum.setText("0.00");

        addlistbutton.setBackground(new java.awt.Color(204, 204, 204));
        addlistbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addlistbutton.setText("+เพิ่มรายการ");
        addlistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlistbuttonActionPerformed(evt);
            }
        });

        notelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        notelabel.setText("หมายเหตุ:");

        percentlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        percentlabel.setText("%");

        totalmoneylabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalmoneylabel.setText("รวมเป็นเงิน:");

        totaldiscountlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totaldiscountlabel.setText("ราคาหลังหักส่วนลด:");

        alltotallabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alltotallabel.setText("จํานวนเงินรวมทั้งสิ้น:");

        alltotalnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alltotalnum.setText("0.00");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("0.00");

        discountnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        discountnum.setText("0.00");

        totaldiscountnum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totaldiscountnum.setText("0.00");

        discounttext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discounttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discounttextActionPerformed(evt);
            }
        });

        discountlabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        discountlabel.setText("ส่วนลด");

        infotext.setColumns(20);
        infotext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        infotext.setRows(5);
        jScrollPane1.setViewportView(infotext);

        notetextarea.setColumns(20);
        notetextarea.setRows(5);
        jScrollPane2.setViewportView(notetextarea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(officetext, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(nametext)
                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ziptext)
                            .addComponent(taxidtext)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(totalnum, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(totallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sellerlabel)
                                    .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datetext, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sellertext, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(detaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailtext))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(projectlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(projecttext, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(Refnumlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(refnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addlistbutton)
                                    .addComponent(notelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(688, 688, 688)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(totaldiscountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(totaldiscountnum))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(alltotallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(alltotalnum))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(discountlabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(discounttext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(percentlabel))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(totalmoneylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(discountnum, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(namelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infolabel)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(totallabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalnum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datelabel)
                            .addComponent(datetext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sellerlabel)
                            .addComponent(sellertext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ziptext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taxidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(officetext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Refnumlabel)
                    .addComponent(refnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectlabel)
                    .addComponent(projecttext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detaillabel)
                    .addComponent(detailtext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalmoneylabel)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addlistbutton)
                        .addComponent(jLabel27)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notelabel)
                            .addComponent(discountnum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discounttext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountlabel)
                            .addComponent(percentlabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totaldiscountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaldiscountnum))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alltotallabel)
                            .addComponent(alltotalnum))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        serielabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        serielabel.setText("QT202420002");

        savebutton.setBackground(new java.awt.Color(51, 204, 0));
        savebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        savebutton.setForeground(new java.awt.Color(255, 255, 255));
        savebutton.setText("บันทึกเอกสาร");

        headerlabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headerlabel.setText("สร้างใบเสร็จรับเงิน");

        closebutton.setBackground(new java.awt.Color(255, 0, 51));
        closebutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("ปิดหน้าต่าง");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serielabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(headerlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serielabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addlistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlistbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addlistbuttonActionPerformed

    private void officetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officetextActionPerformed

    private void taxidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxidtextActionPerformed

    private void ziptextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ziptextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ziptextActionPerformed

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextActionPerformed

    private void sellertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellertextActionPerformed

    private void datetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetextActionPerformed

    private void refnumtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refnumtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refnumtextActionPerformed

    private void detailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailtextActionPerformed

    private void projecttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projecttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projecttextActionPerformed

    private void namepricetext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namepricetext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namepricetext1ActionPerformed

    private void namepricetext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namepricetext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namepricetext2ActionPerformed

    private void quantitytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytextActionPerformed

    private void unittextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unittextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unittextActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        // TODO add your handling code here:
        Home registerForm = new Home();
        registerForm.setVisible(true);
        closebutton.addActionListener(new Receipt());
    }//GEN-LAST:event_closebuttonActionPerformed

    private void discounttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discounttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discounttextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}

// create UI here...

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Refnumlabel;
    private javax.swing.JButton addlistbutton;
    private javax.swing.JLabel alltotallabel;
    private javax.swing.JLabel alltotalnum;
    private javax.swing.JButton closebutton;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField datetext;
    private javax.swing.JLabel detaillabel;
    private javax.swing.JTextField detailtext;
    private javax.swing.JLabel discountlabel;
    private javax.swing.JLabel discountnum;
    private javax.swing.JTextField discounttext;
    private javax.swing.JLabel headerlabel;
    private javax.swing.JLabel infolabel;
    private javax.swing.JTextArea infotext;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel namepricelabel;
    private javax.swing.JTextField namepricetext1;
    private javax.swing.JTextField namepricetext2;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel notelabel;
    private javax.swing.JTextArea notetextarea;
    private javax.swing.JLabel numlabel;
    private javax.swing.JTextField officetext;
    private javax.swing.JLabel percentlabel;
    private javax.swing.JLabel perpricelabel;
    private javax.swing.JLabel projectlabel;
    private javax.swing.JTextField projecttext;
    private javax.swing.JLabel quantitylabel;
    private javax.swing.JTextField quantitytext;
    private javax.swing.JTextField refnumtext;
    private javax.swing.JButton savebutton;
    private javax.swing.JLabel sellerlabel;
    private javax.swing.JTextField sellertext;
    private javax.swing.JLabel serielabel;
    private javax.swing.JTextField taxidtext;
    private javax.swing.JLabel totaldiscountlabel;
    private javax.swing.JLabel totaldiscountnum;
    private javax.swing.JLabel totallabel;
    private javax.swing.JLabel totalmoneylabel;
    private javax.swing.JLabel totalnum;
    private javax.swing.JLabel totalnumnum;
    private javax.swing.JLabel totalpricelabel;
    private javax.swing.JTextField unittext;
    private javax.swing.JTextField ziptext;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
