package project;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;
import java.io.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author oatsu
 */
public class Report extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        ReportMainPanel = new javax.swing.JPanel();
        NavBarPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        usethisDashboard = new javax.swing.JLabel();
        LogoIconLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        UserName = new javax.swing.JLabel();
        EmailUser = new javax.swing.JLabel();
        BottomProfileUserReporting = new javax.swing.JLabel();
        DocumentPanelButton = new javax.swing.JPanel();
        IconDocument = new javax.swing.JLabel();
        Document = new javax.swing.JComboBox<>();
        jButtonHome = new javax.swing.JButton();
        jButtonProject = new javax.swing.JButton();
        jButtonReporting = new javax.swing.JButton();
        jButtonUsers = new javax.swing.JButton();
        jButtonTax = new javax.swing.JButton();
        jButtonSetting = new javax.swing.JButton();
        ReportDashboard = new javax.swing.JPanel();
        ReportingOverview = new javax.swing.JLabel();
        IconbellReport = new javax.swing.JLabel();
        DateLabelReport = new javax.swing.JLabel();
        PanelTopProfileReport = new javax.swing.JPanel();
        TopProfileUser = new javax.swing.JLabel();
        ProfileNumber = new javax.swing.JLabel();
        YourbusinessPanel = new javax.swing.JPanel();
        YouBusinessReportLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        ProfitPanel = new javax.swing.JPanel();
        ProfitLabel = new javax.swing.JLabel();
        IncomePanel = new javax.swing.JPanel();
        IncomeLabel = new javax.swing.JLabel();
        ExpensesPanel = new javax.swing.JPanel();
        ExpensesLabel = new javax.swing.JLabel();
        EfficiencyPanelLeft = new javax.swing.JPanel();
        EfficiencyPanelRight = new javax.swing.JPanel();
        EfficiencyLabel = new javax.swing.JLabel();
        ProfitabilityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frame2"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1020));

        ReportMainPanel.setLayout(new java.awt.BorderLayout());

        NavBarPanel.setBackground(new java.awt.Color(255, 255, 255));
        NavBarPanel.setPreferredSize(new java.awt.Dimension(340, 1020));

        jSeparator1.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator1.setForeground(new java.awt.Color(136, 136, 136));

        usethisDashboard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        usethisDashboard.setText("Usethis Dashboard");

        LogoIconLabel.setIcon(new javax.swing.ImageIcon("D:\\OOP JAVA LAB\\Project\\src\\image\\Logo.png.png")); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator2.setForeground(new java.awt.Color(136, 136, 136));

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UserName.setText("Username");

        EmailUser.setForeground(new java.awt.Color(136, 136, 136));
        EmailUser.setText("Email");

        BottomProfileUserReporting.setIcon(new javax.swing.ImageIcon("D:\\OOP JAVA LAB\\Project\\src\\image\\Ellipse 2 (1).png")); // NOI18N

        DocumentPanelButton.setBackground(new java.awt.Color(255, 255, 255));

        IconDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_page-edit.png"))); // NOI18N

        Document.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Document.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document", "Quotation", "Recipt" }));
        Document.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentActionPerformed(evt);
            }

            private void DocumentActionPerformed(ActionEvent evt) {
                String selectedDocument = (String) Document.getSelectedItem();
    
                switch (selectedDocument) {
                    case "Document":
                        break;
                    case "Quotation":
                        openQuotition();
                        break;
                    case "Recipt":
                        openReceipt();
                        break;
                    default:
                         break;
                }
            }
        });

        javax.swing.GroupLayout DocumentPanelButtonLayout = new javax.swing.GroupLayout(DocumentPanelButton);
        DocumentPanelButton.setLayout(DocumentPanelButtonLayout);
        DocumentPanelButtonLayout.setHorizontalGroup(
            DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(IconDocument)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Document, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DocumentPanelButtonLayout.setVerticalGroup(
            DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DocumentPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Document)
                    .addGroup(DocumentPanelButtonLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(IconDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_home-simple-door.png"))); // NOI18N
        jButtonHome.setText("  Home");
        jButtonHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonProject.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_app-window.png"))); // NOI18N
        jButtonProject.setText("  Project");
        jButtonProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonProject.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjectActionPerformed(evt);
            }
        });

        jButtonReporting.setBackground(new java.awt.Color(224, 227, 232));
        jButtonReporting.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonReporting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_stats-report.png"))); // NOI18N
        jButtonReporting.setText("  Reporting");
        jButtonReporting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonReporting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportingActionPerformed(evt);
            }
        });

        jButtonUsers.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_user-square.png"))); // NOI18N
        jButtonUsers.setText("  Users");
        jButtonUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonUsers.setHideActionText(true);
        jButtonUsers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsersActionPerformed(evt);
            }
        });

        jButtonTax.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_calculator.png"))); // NOI18N
        jButtonTax.setText("  Tax");
        jButtonTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonTax.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxActionPerformed(evt);
            }
        });

        jButtonSetting.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconoir_settings.png"))); // NOI18N
        jButtonSetting.setText("  Setting");
        jButtonSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButtonSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarPanelLayout = new javax.swing.GroupLayout(NavBarPanel);
        NavBarPanel.setLayout(NavBarPanelLayout);
        NavBarPanelLayout.setHorizontalGroup(
            NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarPanelLayout.createSequentialGroup()
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                        .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(LogoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usethisDashboard))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(BottomProfileUserReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UserName)
                                    .addComponent(EmailUser))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavBarPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonReporting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(NavBarPanelLayout.createSequentialGroup()
                                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DocumentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        NavBarPanelLayout.setVerticalGroup(
            NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarPanelLayout.createSequentialGroup()
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LogoIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usethisDashboard)
                        .addGap(42, 42, 42)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DocumentPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProject, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(jButtonSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NavBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(UserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailUser))
                    .addGroup(NavBarPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BottomProfileUserReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        ReportMainPanel.add(NavBarPanel, java.awt.BorderLayout.WEST);

        ReportDashboard.setBackground(new java.awt.Color(236, 239, 243));

        ReportingOverview.setBackground(new java.awt.Color(255, 255, 255));
        ReportingOverview.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        ReportingOverview.setText("Reporting Overview");

        IconbellReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ph_bell.png"))); // NOI18N

        DateLabelReport.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        DateLabelReport.setForeground(new java.awt.Color(136, 136, 136));
        DateLabelReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/circum_calendar-date.png"))); // NOI18N
        DateLabelReport.setText("Friday, July 10,2024");

        PanelTopProfileReport.setBackground(new java.awt.Color(255, 255, 255));

        TopProfileUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ellipse 2 (1).png"))); // NOI18N

        ProfileNumber.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ProfileNumber.setText("Number");

        javax.swing.GroupLayout PanelTopProfileReportLayout = new javax.swing.GroupLayout(PanelTopProfileReport);
        PanelTopProfileReport.setLayout(PanelTopProfileReportLayout);
        PanelTopProfileReportLayout.setHorizontalGroup(
            PanelTopProfileReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTopProfileReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopProfileUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ProfileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelTopProfileReportLayout.setVerticalGroup(
            PanelTopProfileReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTopProfileReportLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(TopProfileUser)
                .addGap(18, 18, 18))
            .addGroup(PanelTopProfileReportLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ProfileNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        YourbusinessPanel.setBackground(new java.awt.Color(255, 255, 255));
        YourbusinessPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(236, 239, 243)));

        YouBusinessReportLabel.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        YouBusinessReportLabel.setText("Your Business Report");

        jSeparator4.setBackground(new java.awt.Color(136, 136, 136));
        jSeparator4.setForeground(new java.awt.Color(136, 136, 136));

        ProfitPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProfitPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ProfitLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ProfitLabel.setText("Profit or loss");

        javax.swing.GroupLayout ProfitPanelLayout = new javax.swing.GroupLayout(ProfitPanel);
        ProfitPanel.setLayout(ProfitPanelLayout);
        ProfitPanelLayout.setHorizontalGroup(
            ProfitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfitPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ProfitLabel)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        ProfitPanelLayout.setVerticalGroup(
            ProfitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfitLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        IncomePanel.setBackground(new java.awt.Color(255, 255, 255));
        IncomePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        IncomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        IncomeLabel.setText("Income");

        javax.swing.GroupLayout IncomePanelLayout = new javax.swing.GroupLayout(IncomePanel);
        IncomePanel.setLayout(IncomePanelLayout);
        IncomePanelLayout.setHorizontalGroup(
            IncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(IncomeLabel)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        IncomePanelLayout.setVerticalGroup(
            IncomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IncomeLabel)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        ExpensesPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExpensesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ExpensesLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ExpensesLabel.setText("Expenses");

        javax.swing.GroupLayout ExpensesPanelLayout = new javax.swing.GroupLayout(ExpensesPanel);
        ExpensesPanel.setLayout(ExpensesPanelLayout);
        ExpensesPanelLayout.setHorizontalGroup(
            ExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpensesPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ExpensesLabel)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        ExpensesPanelLayout.setVerticalGroup(
            ExpensesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpensesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExpensesLabel)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        EfficiencyPanelLeft.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyPanelLeft.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout EfficiencyPanelLeftLayout = new javax.swing.GroupLayout(EfficiencyPanelLeft);
        EfficiencyPanelLeft.setLayout(EfficiencyPanelLeftLayout);
        EfficiencyPanelLeftLayout.setHorizontalGroup(
            EfficiencyPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EfficiencyPanelLeftLayout.setVerticalGroup(
            EfficiencyPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        EfficiencyPanelRight.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyPanelRight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout EfficiencyPanelRightLayout = new javax.swing.GroupLayout(EfficiencyPanelRight);
        EfficiencyPanelRight.setLayout(EfficiencyPanelRightLayout);
        EfficiencyPanelRightLayout.setHorizontalGroup(
            EfficiencyPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EfficiencyPanelRightLayout.setVerticalGroup(
            EfficiencyPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        EfficiencyLabel.setBackground(new java.awt.Color(255, 255, 255));
        EfficiencyLabel.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        EfficiencyLabel.setText("Efficiency");

        ProfitabilityLabel.setBackground(new java.awt.Color(255, 255, 255));
        ProfitabilityLabel.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        ProfitabilityLabel.setText("Profitability");

        javax.swing.GroupLayout YourbusinessPanelLayout = new javax.swing.GroupLayout(YourbusinessPanel);
        YourbusinessPanel.setLayout(YourbusinessPanelLayout);
        YourbusinessPanelLayout.setHorizontalGroup(
            YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                        .addComponent(YouBusinessReportLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YourbusinessPanelLayout.createSequentialGroup()
                        .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                                .addComponent(ProfitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IncomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(EfficiencyPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EfficiencyPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExpensesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                        .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProfitabilityLabel)
                            .addComponent(EfficiencyLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        YourbusinessPanelLayout.setVerticalGroup(
            YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YourbusinessPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(YouBusinessReportLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(ProfitabilityLabel)
                .addGap(26, 26, 26)
                .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(IncomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExpensesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProfitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(EfficiencyLabel)
                .addGap(31, 31, 31)
                .addGroup(YourbusinessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EfficiencyPanelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EfficiencyPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout ReportDashboardLayout = new javax.swing.GroupLayout(ReportDashboard);
        ReportDashboard.setLayout(ReportDashboardLayout);
        ReportDashboardLayout.setHorizontalGroup(
            ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportDashboardLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ReportDashboardLayout.createSequentialGroup()
                        .addComponent(IconbellReport)
                        .addGap(18, 18, 18)
                        .addComponent(PanelTopProfileReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ReportDashboardLayout.createSequentialGroup()
                            .addComponent(ReportingOverview)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateLabelReport))
                        .addComponent(YourbusinessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        ReportDashboardLayout.setVerticalGroup(
            ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportDashboardLayout.createSequentialGroup()
                        .addComponent(PanelTopProfileReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportDashboardLayout.createSequentialGroup()
                        .addComponent(IconbellReport)
                        .addGap(31, 31, 31)))
                .addGroup(ReportDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportDashboardLayout.createSequentialGroup()
                        .addComponent(DateLabelReport)
                        .addGap(43, 43, 43)
                        .addComponent(YourbusinessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ReportingOverview))
                .addGap(21, 21, 21))
        );

        ReportMainPanel.add(ReportDashboard, java.awt.BorderLayout.CENTER);

        getContentPane().add(ReportMainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void DocumentComboboxActionPerformed(java.awt.event.ActionEvent evt) {                                                  

}
    private void openQuotition() {
    Quotition registerForm = new Quotition();
    registerForm.setVisible(true);
    }
    
    private void openReceipt() {
    Receipt registerForm = new Receipt();
    registerForm.setVisible(true);
    }
                                        

    private void jButtonUsersActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButtonTaxActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButtonProjectActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        Projecct registerForm = new Projecct();
        registerForm.setVisible(true);
        jButtonProject.addActionListener(new Report());
    }                                              

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        Home registerForm = new Home();
        registerForm.setVisible(true);
        jButtonHome.addActionListener(new Report());
    }                                           

    private void jButtonReportingActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        Report registerForm = new Report();
        registerForm.setVisible(true);
        jButtonReporting.addActionListener(new Report());
    }                                                

    private void jButtonSettingActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BottomProfileUserReporting;
    private javax.swing.JLabel DateLabelReport;
    private javax.swing.JComboBox<String> Document;
    private javax.swing.JPanel DocumentPanelButton;
    private javax.swing.JLabel EfficiencyLabel;
    private javax.swing.JPanel EfficiencyPanelLeft;
    private javax.swing.JPanel EfficiencyPanelRight;
    private javax.swing.JLabel EmailUser;
    private javax.swing.JLabel ExpensesLabel;
    private javax.swing.JPanel ExpensesPanel;
    private javax.swing.JLabel IconDocument;
    private javax.swing.JLabel IconbellReport;
    private javax.swing.JLabel IncomeLabel;
    private javax.swing.JPanel IncomePanel;
    private javax.swing.JLabel LogoIconLabel;
    private javax.swing.JPanel NavBarPanel;
    private javax.swing.JPanel PanelTopProfileReport;
    private javax.swing.JLabel ProfileNumber;
    private javax.swing.JLabel ProfitLabel;
    private javax.swing.JPanel ProfitPanel;
    private javax.swing.JLabel ProfitabilityLabel;
    private javax.swing.JPanel ReportDashboard;
    private javax.swing.JPanel ReportMainPanel;
    private javax.swing.JLabel ReportingOverview;
    private javax.swing.JLabel TopProfileUser;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel YouBusinessReportLabel;
    private javax.swing.JPanel YourbusinessPanel;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonProject;
    private javax.swing.JButton jButtonReporting;
    private javax.swing.JButton jButtonSetting;
    private javax.swing.JButton jButtonTax;
    private javax.swing.JButton jButtonUsers;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel usethisDashboard;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
